# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_audit.ui'
#
# Created: Wed May  1 17:01:10 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_audit(object):
    def setupUi(self, audit):
        audit.setObjectName(_fromUtf8("audit"))
        audit.resize(810, 568)
        self.gridLayout_6 = QtGui.QGridLayout(audit)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 3, 1, 1)
        self.widget_2 = QtGui.QWidget(audit)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.stopButton = QtGui.QPushButton(self.widget_2)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.gridLayout_3.addWidget(self.stopButton, 0, 2, 1, 1)
        self.searchButton = QtGui.QPushButton(self.widget_2)
        self.searchButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.gridLayout_3.addWidget(self.searchButton, 0, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.widget_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_3.addWidget(self.progressBar, 1, 1, 1, 2)
        self.gridLayout_6.addWidget(self.widget_2, 1, 4, 1, 1)
        self.widget = QtGui.QWidget(audit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.layerCombo = QtGui.QComboBox(self.widget)
        self.layerCombo.setObjectName(_fromUtf8("layerCombo"))
        self.gridLayout.addWidget(self.layerCombo, 0, 1, 1, 1)
        self.featureEdit = QtGui.QLineEdit(self.widget)
        self.featureEdit.setObjectName(_fromUtf8("featureEdit"))
        self.gridLayout.addWidget(self.featureEdit, 0, 3, 1, 2)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.pkeyCombo = QtGui.QComboBox(self.widget)
        self.pkeyCombo.setMinimumSize(QtCore.QSize(40, 0))
        self.pkeyCombo.setObjectName(_fromUtf8("pkeyCombo"))
        self.gridLayout.addWidget(self.pkeyCombo, 0, 8, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.gridLayout_6.addWidget(self.widget, 0, 0, 1, 5)
        self.groupBox_2 = QgsCollapsibleGroupBoxBasic(audit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setProperty("collapsed", True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setMargin(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.searchOnlyGeometry = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchOnlyGeometry.sizePolicy().hasHeightForWidth())
        self.searchOnlyGeometry.setSizePolicy(sizePolicy)
        self.searchOnlyGeometry.setObjectName(_fromUtf8("searchOnlyGeometry"))
        self.gridLayout_8.addWidget(self.searchOnlyGeometry, 1, 0, 1, 3)
        self.searchDeletes = QtGui.QCheckBox(self.groupBox_2)
        self.searchDeletes.setChecked(True)
        self.searchDeletes.setObjectName(_fromUtf8("searchDeletes"))
        self.gridLayout_8.addWidget(self.searchDeletes, 0, 2, 1, 1)
        self.searchBefore = QtGui.QCheckBox(self.groupBox_2)
        self.searchBefore.setObjectName(_fromUtf8("searchBefore"))
        self.gridLayout_8.addWidget(self.searchBefore, 1, 4, 1, 1)
        self.searchBeforeDate = QtGui.QDateTimeEdit(self.groupBox_2)
        self.searchBeforeDate.setCalendarPopup(True)
        self.searchBeforeDate.setObjectName(_fromUtf8("searchBeforeDate"))
        self.gridLayout_8.addWidget(self.searchBeforeDate, 1, 5, 1, 1)
        self.searchUpdates = QtGui.QCheckBox(self.groupBox_2)
        self.searchUpdates.setChecked(True)
        self.searchUpdates.setObjectName(_fromUtf8("searchUpdates"))
        self.gridLayout_8.addWidget(self.searchUpdates, 0, 1, 1, 1)
        self.searchAfter = QtGui.QCheckBox(self.groupBox_2)
        self.searchAfter.setObjectName(_fromUtf8("searchAfter"))
        self.gridLayout_8.addWidget(self.searchAfter, 0, 4, 1, 1)
        self.searchInserts = QtGui.QCheckBox(self.groupBox_2)
        self.searchInserts.setChecked(True)
        self.searchInserts.setObjectName(_fromUtf8("searchInserts"))
        self.gridLayout_8.addWidget(self.searchInserts, 0, 0, 1, 1)
        self.searchAfterDate = QtGui.QDateTimeEdit(self.groupBox_2)
        self.searchAfterDate.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.searchAfterDate.setDate(QtCore.QDate(1970, 1, 1))
        self.searchAfterDate.setCalendarPopup(True)
        self.searchAfterDate.setObjectName(_fromUtf8("searchAfterDate"))
        self.gridLayout_8.addWidget(self.searchAfterDate, 0, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.splitter = QtGui.QSplitter(audit)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.historyPanel = QtGui.QWidget(self.splitter)
        self.historyPanel.setObjectName(_fromUtf8("historyPanel"))
        self.gridLayout_4 = QtGui.QGridLayout(self.historyPanel)
        self.gridLayout_4.setMargin(6)
        self.gridLayout_4.setSpacing(3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.columnChooserButton = QtGui.QToolButton(self.historyPanel)
        self.columnChooserButton.setObjectName(_fromUtf8("columnChooserButton"))
        self.gridLayout_4.addWidget(self.columnChooserButton, 1, 1, 1, 1)
        self.panShowGeometry = QtGui.QCheckBox(self.historyPanel)
        self.panShowGeometry.setChecked(True)
        self.panShowGeometry.setObjectName(_fromUtf8("panShowGeometry"))
        self.gridLayout_4.addWidget(self.panShowGeometry, 1, 0, 1, 1)
        self.loggedActionsWidget = QtGui.QWidget(self.historyPanel)
        self.loggedActionsWidget.setObjectName(_fromUtf8("loggedActionsWidget"))
        self.gridLayout_4.addWidget(self.loggedActionsWidget, 0, 0, 1, 2)
        self.featurePanel = QtGui.QWidget(self.splitter)
        self.featurePanel.setObjectName(_fromUtf8("featurePanel"))
        self.gridLayout_5 = QtGui.QGridLayout(self.featurePanel)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.restoreButton = QtGui.QPushButton(self.featurePanel)
        self.restoreButton.setObjectName(_fromUtf8("restoreButton"))
        self.gridLayout_5.addWidget(self.restoreButton, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 0, 1, 1)
        self.differenceViewerWidget = QtGui.QWidget(self.featurePanel)
        self.differenceViewerWidget.setObjectName(_fromUtf8("differenceViewerWidget"))
        self.gridLayout_5.addWidget(self.differenceViewerWidget, 0, 0, 1, 3)
        self.gridLayout_6.addWidget(self.splitter, 3, 0, 1, 5)

        self.retranslateUi(audit)
        QtCore.QMetaObject.connectSlotsByName(audit)

    def retranslateUi(self, audit):
        audit.setWindowTitle(QtGui.QApplication.translate("audit", "Postgres 91 plus Auditor :: search history", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("audit", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("audit", "search", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("audit", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("audit", "Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("audit", "Primary key", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("audit", "Advanced search", None, QtGui.QApplication.UnicodeUTF8))
        self.searchOnlyGeometry.setText(QtGui.QApplication.translate("audit", "Search only for geometry changes", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDeletes.setText(QtGui.QApplication.translate("audit", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBefore.setText(QtGui.QApplication.translate("audit", "before", None, QtGui.QApplication.UnicodeUTF8))
        self.searchUpdates.setText(QtGui.QApplication.translate("audit", "Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.searchAfter.setText(QtGui.QApplication.translate("audit", "after", None, QtGui.QApplication.UnicodeUTF8))
        self.searchInserts.setText(QtGui.QApplication.translate("audit", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.columnChooserButton.setText(QtGui.QApplication.translate("audit", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.panShowGeometry.setText(QtGui.QApplication.translate("audit", "Pan and show geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.restoreButton.setText(QtGui.QApplication.translate("audit", "Restore feature", None, QtGui.QApplication.UnicodeUTF8))

from qgis.gui import QgsCollapsibleGroupBoxBasic
